VERSION 0.6
FROM openjdk:11
WORKDIR /app

build:
    FROM maven:3.6.3-openjdk-11
    COPY src ./src
    COPY pom.xml ./
    RUN mvn -f ./pom.xml clean package
    SAVE ARTIFACT ./target/pii-detection*jar-with-dependencies.jar pii-detection.jar AS LOCAL pii-detection.jar

docker:
    ARG ver='0.0.0'
    COPY +build/pii-detection.jar .
    EXPOSE 5000
    CMD ["java", "-jar", "pii-detection.jar"]
    SAVE IMAGE --push rtdl/module-pii-detection:$ver
    SAVE IMAGE --push rtdl/module-pii-detection:latest
