VERSION 0.6
FROM golang:1.17-alpine
WORKDIR /app
ENV GIN_MODE=release

build:
    COPY go.mod go.sum ingest-service.go ./
    RUN go mod download -x
    RUN go build -o ./ingest-service
    SAVE ARTIFACT ./ingest-service ingest-service AS LOCAL ingest-service

docker:
    ARG ver='0.0.0'
    COPY +build/ingest-service .
    EXPOSE 8080
    CMD [ "./ingest-service" ]
    SAVE IMAGE --push rtdl/rtdl-ingest:$ver
    SAVE IMAGE --push rtdl/rtdl-ingest:latest
